github: [Gamerdudee]                  # GitHub Sponsors (if enabled)
patreon:                             # Leave blank if not used
open_collective:                     # Leave blank if not used
ko_fi:                               # Ko-fi username if used
tidelift:                            # Leave blank unless using Tidelift
community_bridge:                    # Leave blank
liberapay: mrholmes                  # Liberapay username (optional)
issuehunt:                           # Leave blank unless enabled
lfx_crowdfunding:                    # Leave blank
polar:                               # Leave blank
buy_me_a_coffee: mrholmes            # Replace with your username
thanks_dev:                          # Optional
custom: ['https://holmesenforcementmodel.github.io/donate']
